### ISSUE TITLE
Installing serman on a windows server with no internet connection

### ISSUE THREAD

**Issue by PeterGrandcourt** [kflu/serman#6]
Hi,
I have just got this up and running on my local PC and it seems to work fine.
I'm very relieved at having found something that creates the windows service reliably, so many thanks for this.

but....

The next step is for me to put it on a windows server with no internet connection.

What I would typically do is the following.
----------------------------------------------

1. Clone the project on my PC
2. Run npm install
3. Edit the package.json adding a bundledDependencies section with all libs mentioned in the dependency section.
4. run npm pack to get a tgz file that I can use to install on the server.
5. On the target server with no internet connection, run
6. npm install -g --no-optional targzfile.tzg

When I do this with serman it fails with an error because the serman.exe file is not in the tgz created by npm pack. 
npm pack just zips up the all the files in the directory. 
So I checked, and it seems that npm install on the project doesn't create everything that is needed. Presumably there is a missing c# build step that is being used to build the package that is on npmjs.com

Attempts to install pre-compiled binaries
---------------------------------------------
Looking at the 'releases' page there is a serman.zip containing the binaries.
But there are no instructions what to do with this. Could you provide some please?

Thanks

Peter

**Comment by kflu** [comment]
Doing `npm install` without pre-building the c# project in hope of making a usable package wouldn't work. This is really a .NET project - I merely use NPM as a convenient deployment channel for **pre-built** serman package. But if you do have a .NET development environment, building it would be really easily. I'll update the README to provide that info.

To solve your problem, you can do any of the below:

You just npm install it on a machine with internet. Find where serman.exe is installed, copy them over to your server. Or:

You can take the serman.zip from release and unzip it in a directory and run serman from there. Although that release is not the most up-to-date one (probably fine for your use case. you can try it). 

If you do want to use the latest bits, you can build it yourself with a .NET dev environment (msbuild), or wait for me to publish it as a release.

**Comment by kflu** [comment]
I updated the README on how to install it from Github released package. I created #7 to provide instruction on building serman from source. I'll also publish the latest binary on both github release and NPM (tracked by #8).

Hope this helps.

**Comment by PeterGrandcourt** [comment]
Thanks for the response.
It might be worth noting that this is dependent on .NET Framework 4.0.
